config/routes.rb
Chartme::Application.routes.draw do

  resources :jobs do
    collection { post :import }
  end

  resources :titles

  resources :githubers do
    collection { post :import }
  end

  get "pages/home"

  resources :itheros do
    collection { post :import }
  end

  root to: 'pages#home'

end

app/models/job.rb
#encoding: UTF-8
class Job < ActiveRecord::Base
  
  attr_accessible :category, :company, :date, :is_active, :responses, :title, :city, :datestr

  scope :kiev, where('city like ?', 'Киев')
  scope :kharkov, where('city like?','Харьков')
  scope :lviv, where('city like','Львів')

  scope :pm, where(:category => 'Project Manager')
  scope :qa, where(:categroy => 'QA')

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      job = Job.create! row.to_hash
      job.save
    end
  end

  def self.count_for(category)
    where(:category => category).count
  end

  def self.average_for(category)
    where(:category => category).average(:responses)
  end

  def self.average_for_comp(company)
    where(:company => company).average(:responses)
  end

  def self.count_jobs(company)
    where(:company => company).count
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def import
    Job.import(params[:file])
    redirect_to root_url, notice: "Jobs imported."
  end
  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @jobs }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(params[:job])

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update_attributes(params[:job])
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :responses %><br />
    <%= f.number_field :responses %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/_import.html.haml
%h2 Import Jobs
= form_tag import_jobs_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Import"

%br
%br

app/views/jobs/edit.html.erb
<h1>Editing job</h1>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.haml
#article
  %h1
    ="Рейтинг вакансий по откликам на jobs.dou.ua"
  .text
    =link_to "http://jobs.dou.ua/", "http://jobs.dou.ua/"
  .text
    ="За последние три месяца насобиралось порядка 1000 откликов на вакансии. Представляем здесь рейтинг 'горячих' вакансий, компаний, технологий."
  .text
    ="Лидерами рынка стали вакансии менеджмента и QA."
  #rotated.chart{:style => "width: 860px; height: 500px;"}
  .text
    ="Больше всего компании предлагают работы для специализаций QA, .NET, Java, PHP, C++:"
  #grouped.chart{:style => "width: 860px; height: 500px;"}
  .text
    ="Если рассматривать самые популярные специализации, то с среднем отклики выглядят так:"
  #average.chart{:style => "width: 860px; height: 300px;"}
  .text
    ="Если рассматривать специализации, которые в принципе получили отклики:"
  #average_cat.chart{:style => "width: 860px; height: 400px;"}
  .text
    ="Теперь по компаниям. Больше всего вакансий предлагают кампании:"
  #pie_comp.chart{:style => "width: 860px; height: 500px;"}
  .text
    ="Спрос на вакансии выглядит вот так:"
  #average_comp.chart{:style => "width: 860px; height: 200px;"}
  .text
    ="А больше всего откликов получили в основном компании из категории Other:"
  #average_comp_top.chart{:style => "width: 860px; height: 400px;"}
  #line_bar.chart{:style => "width: 860px; height: 500px;display:none;"}
  #line_bar_ua.chart{:style => "width: 860px; height: 500px;display:none;"}
  #line_bar_bel.chart{:style => "width: 860px; height: 500px;display:none;"}

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @job.title %>
</p>

<p>
  <b>Category:</b>
  <%= @job.category %>
</p>

<p>
  <b>Company:</b>
  <%= @job.company %>
</p>

<p>
  <b>Responses:</b>
  <%= @job.responses %>
</p>

<p>
  <b>Date:</b>
  <%= @job.date %>
</p>

<p>
  <b>Is active:</b>
  <%= @job.is_active %>
</p>


<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>