config/routes.rb
Chartme::Application.routes.draw do

  resources :jobs do
    collection { post :import }
  end

  resources :titles

  resources :githubers do
    collection { post :import }
  end

  get "pages/home"

  resources :itheros do
    collection { post :import }
  end

  root to: 'pages#home'

end

app/models/githuber.rb
class Githuber < ActiveRecord::Base
  attr_accessible :contributions, :country, :followers, :interests, :language, :link, :location, :name, :reps, :username

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      githuber = Githuber.create! row.to_hash
      githuber.country = 'Belarus'
      githuber.save
    end
  end

end

app/controllers/githubers_controller.rb
class GithubersController < ApplicationController

  def import
    Githuber.import(params[:file])
    redirect_to root_url, notice: "Heroes imported."
  end
  # GET /githubers
  # GET /githubers.json
  def index
    @githubers = Githuber.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @githubers }
    end
  end

  # GET /githubers/1
  # GET /githubers/1.json
  def show
    @githuber = Githuber.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @githuber }
    end
  end

  # GET /githubers/new
  # GET /githubers/new.json
  def new
    @githuber = Githuber.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @githuber }
    end
  end

  # GET /githubers/1/edit
  def edit
    @githuber = Githuber.find(params[:id])
  end

  # POST /githubers
  # POST /githubers.json
  def create
    @githuber = Githuber.new(params[:githuber])

    respond_to do |format|
      if @githuber.save
        format.html { redirect_to @githuber, notice: 'Githuber was successfully created.' }
        format.json { render json: @githuber, status: :created, location: @githuber }
      else
        format.html { render action: "new" }
        format.json { render json: @githuber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /githubers/1
  # PUT /githubers/1.json
  def update
    @githuber = Githuber.find(params[:id])

    respond_to do |format|
      if @githuber.update_attributes(params[:githuber])
        format.html { redirect_to @githuber, notice: 'Githuber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @githuber.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /githubers/1
  # DELETE /githubers/1.json
  def destroy
    @githuber = Githuber.find(params[:id])
    @githuber.destroy

    respond_to do |format|
      format.html { redirect_to githubers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/githubers_helper.rb
module GithubersHelper
end

app/views/githubers/_form.html.erb
<%= form_for(@githuber) do |f| %>
  <% if @githuber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@githuber.errors.count, "error") %> prohibited this githuber from being saved:</h2>

      <ul>
      <% @githuber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :contributions %><br />
    <%= f.text_field :contributions %>
  </div>
  <div class="field">
    <%= f.label :followers %><br />
    <%= f.number_field :followers %>
  </div>
  <div class="field">
    <%= f.label :interests %><br />
    <%= f.text_field :interests %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :link %><br />
    <%= f.text_field :link %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :reps %><br />
    <%= f.number_field :reps %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :country %><br />
    <%= f.text_field :country %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/githubers/_import.html.haml
%h2 Import Githubers
= form_tag import_githubers_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Import"

%br
%br

app/views/githubers/edit.html.erb
<h1>Editing githuber</h1>

<%= render 'form' %>

<%= link_to 'Show', @githuber %> |
<%= link_to 'Back', githubers_path %>

app/views/githubers/index.html.haml
#article
  %h1
    ="Github Топ 10"
  .text
    ="Github вообще очень приятное место, что тут скажешь."
    =link_to "Интересные обновления профилей пользователей,", "http://dou.ua/lenta/news/github-contributions-shiny/"
    ="удобство pull request, просмотра кода(code review), комменты, история коммитов — всё это привлекает настолько, что можно иногда долго смотреть в экран. Ну и конечно, социализация, фолловеры, сегодня речь пойдет о них, о самых популярных пользователях Github России, Украины, и Белоруссии."
  %h2 Россия
  .text
    ="Для начала, немного про Россию. В России цвет Github пишет почти на всех языках, живут в основном в Москве и Петербурге, но иногда и в Омске (например, Quarx2k)"
  #line_bar.chart{:style => "width: 860px; height: 500px;"}
  .text
    ="Российский клуб по интересам:"
  %table
    %th На Github
    %th Интересы
    - Githuber.where(:country=>'Russia').each do |user|
      %tr
        %td
          =link_to user.username, user.link
        %td
          =user.contributions
  %h2 Украина
  .text
    ="Страна должна знать своих героев. В Украине, почти все из Киева, правда победитель (paulmillr) по непроверенным данным — из Харькова, а BloodAxe — из Одессы. Самые популярные языки Javascript и Python."
  #line_bar_ua.chart{:style => "width: 860px; height: 500px;"}
  .text
    ="Украинский клуб по интересам:"
  %table
    %th На Github
    %th Интересы
    - Githuber.where(:country=>'Ukraine').each do |user|
      %tr
        %td
          =link_to user.username, user.link
        %td
          =user.contributions
  .text
    ="И они (почти все) есть на ДОУ:"
    %p
      ="http://dou.ua/users/paulmillr/"
    %p
      ="http://dou.ua/users/mourner/"
    %p
      ="http://dou.ua/users/alexey-kachayev/"
    %p
      ="http://dou.ua/users/piranha"
    %p
      ="/http://dou.ua/users/serge-koval"
    %p
      ="/http://dou.ua/users/alexbeletsky"
    %p
      ="/http://dou.ua/users/chaliy/"
  %h2 Белоруссия
  .text
    ="Белоруссия выбирает Ruby, Java и C#. Пишут в основном в Минске, попадается ещё Гродно (nostra13)."
  #line_bar_bel.chart{:style => "width: 860px; height: 500px;"}
  .text
    ="Белорусский клуб по интересам:"
  %table
    %th На Github
    %th Интересы
    - Githuber.where(:country=>'Belarus').each do |user|
      %tr
        %td
          =link_to user.username, user.link
        %td
          =user.contributions
  %h2 Поиграем
  .text
    = "В судьи кто? Т.е. кто же фолловеры, раз они служат основным критерием популярности? Возьмем для топов России и Украины. Можете нарисовать сами для кого угодно, используя вот эту"
    = link_to "простую штуку", "https://github.com/ezgraphs/R-Programs/blob/master/github_followers.R"
    .text
    ="Тут ещё интересно посмотреть на фолловеров фолловеров, когда у них много фолловеров, то получается какая-то скороговорка:) Точнее, становится интересней и интересней."
    %h4
      ="Github, граф фолловеров для Grigory Bakunov as bobuk (отрисовано по алгоритму Fruchterman-Reingold)"
  =image_tag('bobuk.png', :size => "1200x600")
  .text
    %h4
      ="Github, граф фолловеров для Paul Miller (отрисовано по алгоритму Kamada-Kawai)"
    = link_to "http://dou.ua/users/paulmillr/", "http://dou.ua/users/paulmillr/"
  =image_tag('paulmlr.png', :size => "1200x600")
  .text
    ="И это вроде как минута славы, попробуйте найти себя :) Не переживайте, если не нашли, Github API присылает не всех за раз, да все бы и не поместились."

app/views/githubers/new.html.erb
<h1>New githuber</h1>

<%= render 'form' %>

<%= link_to 'Back', githubers_path %>

app/views/githubers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Contributions:</b>
  <%= @githuber.contributions %>
</p>

<p>
  <b>Followers:</b>
  <%= @githuber.followers %>
</p>

<p>
  <b>Interests:</b>
  <%= @githuber.interests %>
</p>

<p>
  <b>Language:</b>
  <%= @githuber.language %>
</p>

<p>
  <b>Link:</b>
  <%= @githuber.link %>
</p>

<p>
  <b>Location:</b>
  <%= @githuber.location %>
</p>

<p>
  <b>Name:</b>
  <%= @githuber.name %>
</p>

<p>
  <b>Reps:</b>
  <%= @githuber.reps %>
</p>

<p>
  <b>Username:</b>
  <%= @githuber.username %>
</p>

<p>
  <b>Country:</b>
  <%= @githuber.country %>
</p>


<%= link_to 'Edit', edit_githuber_path(@githuber) %> |
<%= link_to 'Back', githubers_path %>