config/routes.rb
Chartme::Application.routes.draw do

  resources :jobs do
    collection { post :import }
  end

  resources :titles

  resources :githubers do
    collection { post :import }
  end

  get "pages/home"

  resources :itheros do
    collection { post :import }
  end

  root to: 'pages#home'

end

app/models/ithero.rb
#encoding: UTF-8
class Ithero < ActiveRecord::Base
  attr_accessible :nothing, :age, :currency, :city, :company_size, :date, :education, :english, :gender, :language, :netwage, :spec_more, :speciality, :tenure, :tenure_current, :user_agent, :wage_diff

  scope :kiev, where(:city => 'Киев')
  scope :kharkov, where(:city => 'Харьков')
  scope :lvov, where(:city => 'Львов')

  scope :dnepr, where(:city => 'Днепропетровск')

  scope :senior, where('speciality like ?','%Senior Software Engineer%')
  scope :middle, where(:speciality => 'Software Engineer')
  scope :junior, where('speciality like ?','%Junior Software Engineer%')

  scope :dollar, where(:currency=>'d')

  scope :male, where(:gender=>'m')
  scope :female, where(:gender=>'f')

  scope :pm, where('speciality like ? or ?','%Project manager%', '%Technical Lead%')
  scope :qa, where('speciality like ?','%QA Engineer%')

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      ithero=Ithero.create! row.to_hash
      ithero.year=2012
      ithero.save
    end
  end

  def self.average_for(speciality)
    where(:language => speciality).where('speciality like ?','%Software Engineer%').average(:netwage)
  end

  def self.average_for_pos(position)
    where(:speciality=>position).average(:netwage)
  end

  def self.diff_for(speciality)
    where(:language => speciality).where('speciality like ?','%Software Engineer%').average(:wage_diff)
  end

  def self.average_for_spec(speciality)
    where('speciality like ?','%speciality%').average(:netwage)
  end

  def self.average
   all.average(:netwage)
  end
  
end

app/controllers/itheros_controller.rb
class ItherosController < ApplicationController

  def import
    Ithero.import(params[:file])
    redirect_to root_url, notice: "Heroes imported."
  end
  # GET /itheros
  # GET /itheros.json
  def index
    @itheros = Ithero.all
    @salaries = ['Java', 'PHP', 'Ruby/Rails'].map { |spec| Ithero.average_for(spec).to_i}
    puts '#{@salaries} ++++++++++++++'

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @itheros }
    end
  end

  # GET /itheros/1
  # GET /itheros/1.json
  def show
    @ithero = Ithero.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ithero }
    end
  end

  # GET /itheros/new
  # GET /itheros/new.json
  def new
    @ithero = Ithero.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ithero }
    end
  end

  # GET /itheros/1/edit
  def edit
    @ithero = Ithero.find(params[:id])
  end

  # POST /itheros
  # POST /itheros.json
  def create
    @ithero = Ithero.new(params[:ithero])

    respond_to do |format|
      if @ithero.save
        format.html { redirect_to @ithero, notice: 'Ithero was successfully created.' }
        format.json { render json: @ithero, status: :created, location: @ithero }
      else
        format.html { render action: "new" }
        format.json { render json: @ithero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /itheros/1
  # PUT /itheros/1.json
  def update
    @ithero = Ithero.find(params[:id])

    respond_to do |format|
      if @ithero.update_attributes(params[:ithero])
        format.html { redirect_to @ithero, notice: 'Ithero was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @ithero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itheros/1
  # DELETE /itheros/1.json
  def destroy
    @ithero = Ithero.find(params[:id])
    @ithero.destroy

    respond_to do |format|
      format.html { redirect_to itheros_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/itheros_helper.rb
module ItherosHelper
end

app/views/itheros/_form.html.erb
<%= form_for(@ithero) do |f| %>
  <% if @ithero.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ithero.errors.count, "error") %> prohibited this ithero from being saved:</h2>

      <ul>
      <% @ithero.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :speciality %><br />
    <%= f.text_field :speciality %>
  </div>
  <div class="field">
    <%= f.label :language %><br />
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :spec_more %><br />
    <%= f.text_field :spec_more %>
  </div>
  <div class="field">
    <%= f.label :tenure %><br />
    <%= f.text_field :tenure %>
  </div>
  <div class="field">
    <%= f.label :tenure_current %><br />
    <%= f.text_field :tenure_current %>
  </div>
  <div class="field">
    <%= f.label :netwage %><br />
    <%= f.number_field :netwage %>
  </div>
  <div class="field">
    <%= f.label :wage_diff %><br />
    <%= f.number_field :wage_diff %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :company_size %><br />
    <%= f.text_field :company_size %>
  </div>
  <div class="field">
    <%= f.label :gender %><br />
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :education %><br />
    <%= f.text_field :education %>
  </div>
  <div class="field">
    <%= f.label :english %><br />
    <%= f.text_field :english %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :user_agent %><br />
    <%= f.text_field :user_agent %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/itheros/_import.html.haml
%h2 Import IT heroes
= form_tag import_itheros_path, multipart: true do
  = file_field_tag :file
  = submit_tag "Import"

%br
%br

app/views/itheros/edit.html.erb
<h1>Editing ithero</h1>

<%= render 'form' %>

<%= link_to 'Show', @ithero %> |
<%= link_to 'Back', itheros_path %>

app/views/itheros/index.html.haml
#article
  %h2 Краткий обзор зарплат
  .text
    ="Зарплатный опрос, декабрь 2012, 4226 анкет, для сравнения прошлые опросы"
    =link_to "май 2012,", "http://dou.ua/lenta/articles/developers-salaries-may-june-2012/"
    =link_to "2011", "http://dou.ua/lenta/articles/developers-salaries-december-2011/" 
    ="и"
    =link_to "2010", "http://dou.ua/lenta/work/salary-survey-report-oct-2010/"
    %br
    = "Обработанные данные доступны в виде "
    = link_to "виджета", "http://jobs.dou.ua/salaries/"
    =", существуют также исходные данные на"
    =link_to "github", 'https://github.com/imax/dou-salaries'
    %br
    %br
    ="Средние зарплаты по основным специализациям выглядят сейчас так:"
  #it_chart.chart{:style => "width: 560px; height: 500px;"}
  .text
    = "Если добавить результаты декабря 2011, можно сравнить увеличение по специализациям."
  #year_chart.chart{:style => "width: 560px; height: 500px;"}
  .text
    = "Также мы видим, что увеличение зарплат не такое уж и большое. Это связано как с увеличением количества middle и junior разработчиков(доля новичков растет), так и с ростом количества разработчиков в других городах, кроме самого дорогого Киева, или даже с увеличением налога ЧПшникам, потому что рассматриваем зарплаты после уплаты налогов. Но мы не будем особо вдаваться в вопросы налогообложения здесь, а посмотрим на зарплаты по синьорам и джуниорам, а потом по городам для объективности. А потом перейдем к самому приросту."
    = "В топ рейтинге разработчиков как всегда лидируют Sr Java."
  #srjr_chart.chart{:style => "width: 560px; height: 500px;"}
  .text
    = "Учитываем, что в Sr Java попадает и Android, а если взять чистый Enterprise, то может, и PM'ов перегонят. И вообще выделение Android было бы неплохо в последующих опросах, в текущих данных пока этого нет.  А вот чтобы стать Senior, например, в среднем требуется сейчас 6 лет, чтобы дорасти до middle 2-3 года:"
  #xp_chart.chart{:style => "width: 560px; height: 300px;"}
  .text 
    ="Если смотреть по городам, больше всего анкет у нас из Киева, Харькова и Львова."
  #golden_chart.chart{:style => "width: 800px; height: 500px;"}
  .text
    ="Во Львове разработчики почти такие же дорогие, как в Киеве, в Харькове подешевле. Ещё дорого в Одессе, и подешевле в Донецке."
  #city_chart.chart{:style => "width: 800px; height: 500px;"}
  .text
    ="Но в целом понятно, что рост зарплат никто не отменял, и дальше мы посмотрим на прибавку, указанную в анкетах."
  #increase_chart.chart{:style => "width: 560px; height: 350px;"}
  .text
    ="На закуску — сравнение средних зарплат по другим специализациям."
  #other_chart.chart{:style => "width: 560px; height: 500px;"}
  .text
    ="Ну и небольшой график по половому признаку. Для значимости статистики, пришлость убрать питонисток и рубиcток, потому что их мало, а получают они много."
  #gender_chart.chart{:style => "width: 560px; height: 500px;"}
  #line_bar.chart{:style => "width: 860px; height: 500px;display:none;"}
  #line_bar_ua.chart{:style => "width: 860px; height: 500px;display:none;"}
  #line_bar_bel.chart{:style => "width: 860px; height: 500px;display:none;"}

app/views/itheros/new.html.erb
<h1>New ithero</h1>

<%= render 'form' %>

<%= link_to 'Back', itheros_path %>

app/views/itheros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Speciality:</b>
  <%= @ithero.speciality %>
</p>

<p>
  <b>Language:</b>
  <%= @ithero.language %>
</p>

<p>
  <b>Spec more:</b>
  <%= @ithero.spec_more %>
</p>

<p>
  <b>Tenure:</b>
  <%= @ithero.tenure %>
</p>

<p>
  <b>Tenure current:</b>
  <%= @ithero.tenure_current %>
</p>

<p>
  <b>Netwage:</b>
  <%= @ithero.netwage %>
</p>

<p>
  <b>Wage diff:</b>
  <%= @ithero.wage_diff %>
</p>

<p>
  <b>City:</b>
  <%= @ithero.city %>
</p>

<p>
  <b>Company size:</b>
  <%= @ithero.company_size %>
</p>

<p>
  <b>Gender:</b>
  <%= @ithero.gender %>
</p>

<p>
  <b>Age:</b>
  <%= @ithero.age %>
</p>

<p>
  <b>Education:</b>
  <%= @ithero.education %>
</p>

<p>
  <b>English:</b>
  <%= @ithero.english %>
</p>

<p>
  <b>Date:</b>
  <%= @ithero.date %>
</p>

<p>
  <b>User agent:</b>
  <%= @ithero.user_agent %>
</p>


<%= link_to 'Edit', edit_ithero_path(@ithero) %> |
<%= link_to 'Back', itheros_path %>