config/routes.rb
Chartme::Application.routes.draw do

  resources :jobs do
    collection { post :import }
  end

  resources :titles

  resources :githubers do
    collection { post :import }
  end

  get "pages/home"

  resources :itheros do
    collection { post :import }
  end

  root to: 'pages#home'

end

app/models/title.rb
class Title < ActiveRecord::Base
  attr_accessible :category, :company, :date, :is_active, :responses
end

app/controllers/titles_controller.rb
class TitlesController < ApplicationController
  # GET /titles
  # GET /titles.json
  def index
    @titles = Title.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @titles }
    end
  end

  # GET /titles/1
  # GET /titles/1.json
  def show
    @title = Title.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @title }
    end
  end

  # GET /titles/new
  # GET /titles/new.json
  def new
    @title = Title.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @title }
    end
  end

  # GET /titles/1/edit
  def edit
    @title = Title.find(params[:id])
  end

  # POST /titles
  # POST /titles.json
  def create
    @title = Title.new(params[:title])

    respond_to do |format|
      if @title.save
        format.html { redirect_to @title, notice: 'Title was successfully created.' }
        format.json { render json: @title, status: :created, location: @title }
      else
        format.html { render action: "new" }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /titles/1
  # PUT /titles/1.json
  def update
    @title = Title.find(params[:id])

    respond_to do |format|
      if @title.update_attributes(params[:title])
        format.html { redirect_to @title, notice: 'Title was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @title.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /titles/1
  # DELETE /titles/1.json
  def destroy
    @title = Title.find(params[:id])
    @title.destroy

    respond_to do |format|
      format.html { redirect_to titles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/titles_helper.rb
module TitlesHelper
end

app/views/titles/_form.html.erb
<%= form_for(@title) do |f| %>
  <% if @title.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@title.errors.count, "error") %> prohibited this title from being saved:</h2>

      <ul>
      <% @title.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :company %><br />
    <%= f.text_field :company %>
  </div>
  <div class="field">
    <%= f.label :responses %><br />
    <%= f.number_field :responses %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/titles/edit.html.erb
<h1>Editing title</h1>

<%= render 'form' %>

<%= link_to 'Show', @title %> |
<%= link_to 'Back', titles_path %>

app/views/titles/index.html.erb
<h1>Listing titles</h1>

<table>
  <tr>
    <th>Category</th>
    <th>Company</th>
    <th>Responses</th>
    <th>Date</th>
    <th>Is active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @titles.each do |title| %>
  <tr>
    <td><%= title.category %></td>
    <td><%= title.company %></td>
    <td><%= title.responses %></td>
    <td><%= title.date %></td>
    <td><%= title.is_active %></td>
    <td><%= link_to 'Show', title %></td>
    <td><%= link_to 'Edit', edit_title_path(title) %></td>
    <td><%= link_to 'Destroy', title, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Title', new_title_path %>

app/views/titles/new.html.erb
<h1>New title</h1>

<%= render 'form' %>

<%= link_to 'Back', titles_path %>

app/views/titles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Category:</b>
  <%= @title.category %>
</p>

<p>
  <b>Company:</b>
  <%= @title.company %>
</p>

<p>
  <b>Responses:</b>
  <%= @title.responses %>
</p>

<p>
  <b>Date:</b>
  <%= @title.date %>
</p>

<p>
  <b>Is active:</b>
  <%= @title.is_active %>
</p>


<%= link_to 'Edit', edit_title_path(@title) %> |
<%= link_to 'Back', titles_path %>